# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/checkpoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/checkpoint.proto',
  package='programl',
  syntax='proto3',
  serialized_pb=_b('\n\x1fprograml/proto/checkpoint.proto\x12\x08programl\"2\n\nCheckpoint\x12\x12\n\nmodel_data\x18\x02 \x01(\x0cJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\x42-\n\x0c\x63om.programlB\x0f\x43heckpointProtoP\x01Z\nprogramlpbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHECKPOINT = _descriptor.Descriptor(
  name='Checkpoint',
  full_name='programl.Checkpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_data', full_name='programl.Checkpoint.model_data', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Checkpoint'] = _CHECKPOINT

Checkpoint = _reflection.GeneratedProtocolMessageType('Checkpoint', (_message.Message,), dict(
  DESCRIPTOR = _CHECKPOINT,
  __module__ = 'programl.proto.checkpoint_pb2'
  # @@protoc_insertion_point(class_scope:programl.Checkpoint)
  ))
_sym_db.RegisterMessage(Checkpoint)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\014com.programlB\017CheckpointProtoP\001Z\nprogramlpb'))
# @@protoc_insertion_point(module_scope)
