# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/repo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/repo.proto',
  package='programl',
  syntax='proto3',
  serialized_pb=_b('\n\x19programl/proto/repo.proto\x12\x08programl\"?\n\x04Repo\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04sha1\x18\x02 \x01(\t\x12\x1c\n\x14\x63reated_ms_timestamp\x18\x03 \x01(\x03\x42*\n\x0c\x63om.programlB\tRepoProtoP\x01Z\nprogramlpb\xf8\x01\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REPO = _descriptor.Descriptor(
  name='Repo',
  full_name='programl.Repo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='programl.Repo.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='programl.Repo.sha1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_ms_timestamp', full_name='programl.Repo.created_ms_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['Repo'] = _REPO

Repo = _reflection.GeneratedProtocolMessageType('Repo', (_message.Message,), dict(
  DESCRIPTOR = _REPO,
  __module__ = 'programl.proto.repo_pb2'
  # @@protoc_insertion_point(class_scope:programl.Repo)
  ))
_sym_db.RegisterMessage(Repo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\014com.programlB\tRepoProtoP\001Z\nprogramlpb\370\001\001'))
# @@protoc_insertion_point(module_scope)
