# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/module.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from programl.proto import features_pb2 as programl_dot_proto_dot_features__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/module.proto',
  package='programl',
  syntax='proto3',
  serialized_pb=_b('\n\x1bprograml/proto/module.proto\x12\x08programl\x1a\x1dprograml/proto/features.proto\"<\n\x06Module\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x12.programl.FeaturesB)\n\x0c\x63om.programlB\x0bModuleProtoP\x01Z\nprogramlpbb\x06proto3')
  ,
  dependencies=[programl_dot_proto_dot_features__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='programl.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='programl.Module.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='features', full_name='programl.Module.features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=132,
)

_MODULE.fields_by_name['features'].message_type = programl_dot_proto_dot_features__pb2._FEATURES
DESCRIPTOR.message_types_by_name['Module'] = _MODULE

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), dict(
  DESCRIPTOR = _MODULE,
  __module__ = 'programl.proto.module_pb2'
  # @@protoc_insertion_point(class_scope:programl.Module)
  ))
_sym_db.RegisterMessage(Module)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\014com.programlB\013ModuleProtoP\001Z\nprogramlpb'))
# @@protoc_insertion_point(module_scope)
