# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deeplearning/ml4pl/graphs/programl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deeplearning/ml4pl/graphs/programl.proto',
  package='ml4pl',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n(deeplearning/ml4pl/graphs/programl.proto\x12\x05ml4pl\"\xb2\x02\n\x0cProgramGraph\x12\x1f\n\x04node\x18\x01 \x03(\x0b\x32\x0b.ml4pl.NodeR\x04node\x12\x1f\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32\x0b.ml4pl.EdgeR\x04\x65\x64ge\x12+\n\x08\x66unction\x18\x03 \x03(\x0b\x32\x0f.ml4pl.FunctionR\x08\x66unction\x12\x0c\n\x01x\x18\x05 \x03(\x03R\x01x\x12\x0c\n\x01y\x18\x06 \x03(\x03R\x01y\x12-\n\x13\x64\x61ta_flow_root_node\x18\x07 \x01(\x05R\x10\x64\x61taFlowRootNode\x12&\n\x0f\x64\x61ta_flow_steps\x18\x08 \x01(\x05R\rdataFlowSteps\x12@\n\x1d\x64\x61ta_flow_positive_node_count\x18\t \x01(\x05R\x19\x64\x61taFlowPositiveNodeCount\"\x1e\n\x08\x46unction\x12\x12\n\x04name\x18\x01 \x02(\tR\x04name\"\xdb\x01\n\x04Node\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x10.ml4pl.Node.TypeR\x04type\x12\x12\n\x04text\x18\x02 \x02(\tR\x04text\x12+\n\x11preprocessed_text\x18\x03 \x02(\tR\x10preprocessedText\x12\x1a\n\x08\x66unction\x18\x04 \x01(\x05R\x08\x66unction\x12\x0c\n\x01x\x18\x05 \x03(\x03R\x01x\x12\x0c\n\x01y\x18\x06 \x03(\x03R\x01y\"4\n\x04Type\x12\r\n\tSTATEMENT\x10\x00\x12\x0e\n\nIDENTIFIER\x10\x01\x12\r\n\tIMMEDIATE\x10\x02\"\xc0\x01\n\x04\x45\x64ge\x12$\n\x04\x66low\x18\x01 \x02(\x0e\x32\x10.ml4pl.Edge.FlowR\x04\x66low\x12\x1f\n\x0bsource_node\x18\x02 \x02(\x05R\nsourceNode\x12)\n\x10\x64\x65stination_node\x18\x03 \x02(\x05R\x0f\x64\x65stinationNode\x12\x1d\n\x08position\x18\x04 \x02(\x05:\x01\x30R\x08position\"\'\n\x04\x46low\x12\x0b\n\x07\x43ONTROL\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x12\x08\n\x04\x43\x41LL\x10\x02\":\n\rProgramGraphs\x12)\n\x05graph\x18\x01 \x03(\x0b\x32\x13.ml4pl.ProgramGraphR\x05graph')
)



_NODE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='ml4pl.Node.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATEMENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDENTIFIER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMMEDIATE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=560,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_NODE_TYPE)

_EDGE_FLOW = _descriptor.EnumDescriptor(
  name='Flow',
  full_name='ml4pl.Edge.Flow',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTROL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=768,
  serialized_end=807,
)
_sym_db.RegisterEnumDescriptor(_EDGE_FLOW)


_PROGRAMGRAPH = _descriptor.Descriptor(
  name='ProgramGraph',
  full_name='ml4pl.ProgramGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='ml4pl.ProgramGraph.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='node', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge', full_name='ml4pl.ProgramGraph.edge', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='edge', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='function', full_name='ml4pl.ProgramGraph.function', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='function', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ml4pl.ProgramGraph.x', index=3,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='x', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ml4pl.ProgramGraph.y', index=4,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='y', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_flow_root_node', full_name='ml4pl.ProgramGraph.data_flow_root_node', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataFlowRootNode', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_flow_steps', full_name='ml4pl.ProgramGraph.data_flow_steps', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataFlowSteps', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_flow_positive_node_count', full_name='ml4pl.ProgramGraph.data_flow_positive_node_count', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataFlowPositiveNodeCount', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=358,
)


_FUNCTION = _descriptor.Descriptor(
  name='Function',
  full_name='ml4pl.Function',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ml4pl.Function.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=390,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='ml4pl.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ml4pl.Node.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='ml4pl.Node.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='text', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preprocessed_text', full_name='ml4pl.Node.preprocessed_text', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='preprocessedText', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='function', full_name='ml4pl.Node.function', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='function', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ml4pl.Node.x', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='x', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ml4pl.Node.y', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='y', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=612,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='ml4pl.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow', full_name='ml4pl.Edge.flow', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='flow', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_node', full_name='ml4pl.Edge.source_node', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='sourceNode', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_node', full_name='ml4pl.Edge.destination_node', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='destinationNode', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='ml4pl.Edge.position', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='position', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EDGE_FLOW,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=807,
)


_PROGRAMGRAPHS = _descriptor.Descriptor(
  name='ProgramGraphs',
  full_name='ml4pl.ProgramGraphs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph', full_name='ml4pl.ProgramGraphs.graph', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='graph', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=809,
  serialized_end=867,
)

_PROGRAMGRAPH.fields_by_name['node'].message_type = _NODE
_PROGRAMGRAPH.fields_by_name['edge'].message_type = _EDGE
_PROGRAMGRAPH.fields_by_name['function'].message_type = _FUNCTION
_NODE.fields_by_name['type'].enum_type = _NODE_TYPE
_NODE_TYPE.containing_type = _NODE
_EDGE.fields_by_name['flow'].enum_type = _EDGE_FLOW
_EDGE_FLOW.containing_type = _EDGE
_PROGRAMGRAPHS.fields_by_name['graph'].message_type = _PROGRAMGRAPH
DESCRIPTOR.message_types_by_name['ProgramGraph'] = _PROGRAMGRAPH
DESCRIPTOR.message_types_by_name['Function'] = _FUNCTION
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['ProgramGraphs'] = _PROGRAMGRAPHS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramGraph = _reflection.GeneratedProtocolMessageType('ProgramGraph', (_message.Message,), dict(
  DESCRIPTOR = _PROGRAMGRAPH,
  __module__ = 'deeplearning.ml4pl.graphs.programl_pb2'
  # @@protoc_insertion_point(class_scope:ml4pl.ProgramGraph)
  ))
_sym_db.RegisterMessage(ProgramGraph)

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTION,
  __module__ = 'deeplearning.ml4pl.graphs.programl_pb2'
  # @@protoc_insertion_point(class_scope:ml4pl.Function)
  ))
_sym_db.RegisterMessage(Function)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'deeplearning.ml4pl.graphs.programl_pb2'
  # @@protoc_insertion_point(class_scope:ml4pl.Node)
  ))
_sym_db.RegisterMessage(Node)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(
  DESCRIPTOR = _EDGE,
  __module__ = 'deeplearning.ml4pl.graphs.programl_pb2'
  # @@protoc_insertion_point(class_scope:ml4pl.Edge)
  ))
_sym_db.RegisterMessage(Edge)

ProgramGraphs = _reflection.GeneratedProtocolMessageType('ProgramGraphs', (_message.Message,), dict(
  DESCRIPTOR = _PROGRAMGRAPHS,
  __module__ = 'deeplearning.ml4pl.graphs.programl_pb2'
  # @@protoc_insertion_point(class_scope:ml4pl.ProgramGraphs)
  ))
_sym_db.RegisterMessage(ProgramGraphs)


# @@protoc_insertion_point(module_scope)
